### PR TITLE
sample authorization plugin does not implement the interface

### PR DESCRIPTION
**Pull request by tulinkry**
The SampleAuthorizationPlugin did not implement the IAuthorizationPlugin interface. This was introduced by #1117 but forgotten by travis.

Also:
Regading the authorization framework we have two new wikis:
- https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Authorization
- https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Groupings

Containing fairly similar things like in doc directory but with .md desing.

### CODE REVIEW

**Comment by tarzanek** [comment]
so shouldn't the sample plugin be built somehow or tested?
that it implements all the ifaces?

**Comment by tarzanek** [comment]
I will merge for now, but I don't like the fact travis doesn't test this build, let's include the build of sample plugin in travis/mvn
